"""'migrate'

Revision ID: fbe95f0b7463
Revises: 
Create Date: 2024-10-29 12:50:52.710316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe95f0b7463'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('date_registration', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_table('user_address',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users_matches',
    sa.Column('id_from', sa.Integer(), nullable=False),
    sa.Column('id_to', sa.Integer(), nullable=True),
    sa.Column('distance_between', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_from')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_matches')
    op.drop_table('user_address')
    op.drop_table('users')
    # ### end Alembic commands ###
